# Generated by Django 5.0.6 on 2024-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('teacher_first_name', models.CharField(max_length=20)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('experience', models.CharField(max_length=20)),
                ('teacher_last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('salary', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
