# Generated by Django 4.2.15 on 2024-08-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_first_name', models.CharField(default='John', max_length=40)),
                ('teacher_last_name', models.CharField(default='Doe', max_length=40)),
                ('teacher_email', models.EmailField(default='email@example.com', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='N/A', max_length=20)),
                ('department', models.CharField(default='General', max_length=20)),
                ('photo', models.ImageField(default='photos/default.jpg', upload_to='photos/')),
                ('address', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('salary', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='student.student')),
            ],
        ),
    ]
