# Generated by Django 5.0.6 on 2024-08-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="id",
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_first_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_last_name",
            field=models.CharField(max_length=40),
        ),
    ]
