# Generated by Django 4.2.15 on 2024-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_last_name',
        ),
    ]
