# Generated by Django 4.2.15 on 2024-08-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_id_teacher_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
    ]
