# Generated by Django 4.2.15 on 2024-08-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_student_id_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
