# Generated by Django 4.2.15 on 2024-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('syllabus', models.CharField(default='No syllabus provided', max_length=200)),
                ('name', models.CharField(default='Unnamed Course', max_length=100)),
                ('department', models.CharField(default='General Studies', max_length=100)),
                ('prerequisites', models.TextField(blank=True, default='None', null=True)),
                ('description', models.TextField(blank=True, default='No description provided', null=True)),
                ('trimester', models.PositiveSmallIntegerField(default=1)),
                ('course_head', models.CharField(default='Not Assigned', max_length=100)),
                ('enrollment_limit', models.IntegerField(default=30)),
            ],
        ),
    ]
