# Generated by Django 5.0.6 on 2024-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('course_type', models.CharField(max_length=20)),
                ('course_duration', models.PositiveSmallIntegerField()),
                ('course_level', models.CharField(max_length=20)),
                ('course_fee', models.CharField(max_length=15)),
                ('course_trainer', models.CharField(max_length=20)),
                ('course_students', models.PositiveSmallIntegerField()),
                ('course_date', models.DateField()),
            ],
        ),
    ]
