# Generated by Django 4.2.15 on 2024-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_trainer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
