# Generated by Django 4.2.15 on 2024-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0002_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_room',
            field=models.ManyToManyField(blank=True, related_name='class_room', to='schoolclass.schoolclass'),
        ),
    ]
