# Generated by Django 4.2.15 on 2024-08-20 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0005_schoolclass_classroom_course_and_more'),
        ('teacher', '0006_alter_teacher_student_id_alter_teacher_teacher_id'),
        ('student', '0007_student_date_of_birth'),
        ('course', '0002_remove_course_course_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='schoolclass.schoolclass'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='course',
            name='course_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(default='course_level', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='course_name', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='course_students',
            field=models.TextField(default='course_students'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='course_type', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.TextField(default='location'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='student.student'),
        ),
    ]
