# Generated by Django 5.0.6 on 2024-07-22 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_number', models.PositiveSmallIntegerField()),
                ('classroom_trainer_name', models.CharField(max_length=20)),
                ('classroom_location', models.CharField(max_length=20)),
                ('classroom_capacity', models.PositiveSmallIntegerField()),
                ('classroom_level', models.CharField(max_length=20)),
                ('classroom_name', models.CharField(max_length=15)),
                ('classroom_days', models.PositiveSmallIntegerField()),
                ('classroom_student_names', models.TextField()),
                ('classroom_course', models.CharField(max_length=25)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
