# Generated by Django 4.2.15 on 2024-08-21 08:07

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolclass',
            fields=[
                ('classroom_number', models.PositiveSmallIntegerField(default=1)),
                ('classroom_location', models.CharField(default='Unknown Location', max_length=100)),
                ('class_capacity', models.PositiveSmallIntegerField(default=0)),
                ('class_code', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_level', models.CharField(default='General', max_length=20)),
                ('class_names', models.CharField(default='Unnamed Class', max_length=100)),
                ('classroom_days', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
