# Generated by Django 5.0.6 on 2024-07-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_number',
        ),
    ]
