# Generated by Django 4.2.15 on 2024-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='classroom_days',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
