# Generated by Django 4.2.15 on 2024-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0002_remove_schoolclass_classroom_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_capacity',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_course',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_days',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_level',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_location',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_name',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_student_names',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom_trainer_name',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='student_id',
        ),
    ]
