# Generated by Django 4.2.15 on 2024-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0003_remove_schoolclass_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='id',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_code',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_names',
            field=models.CharField(default='class_name', max_length=15),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_representative',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
