# Generated by Django 4.2.15 on 2024-08-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_date_of_birth'),
        ('schoolclass', '0004_remove_schoolclass_id_schoolclass_class_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='classroom_course',
            field=models.CharField(default='classroom_course', max_length=25),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='classroom_days',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='classroom_level',
            field=models.CharField(default='level', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='classroom_location',
            field=models.CharField(default='akirachix', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='classroom_number',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
