# Generated by Django 4.2.15 on 2024-08-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_class_enrolled'),
        ('schoolclass', '0004_remove_schoolclass_classroom_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='classroom_days',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_rep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='represented_classes', to='student.student'),
            preserve_default=False,
        ),
    ]
