# Generated by Django 4.2.15 on 2024-08-21 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('end_time', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('classroom', models.CharField(max_length=20)),
                ('day_of_the_week', models.CharField(max_length=25)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('trainer_name', models.CharField(blank=True, max_length=30)),
                ('trainers_assistant_name', models.CharField(blank=True, max_length=30)),
                ('number_of_hours', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
