# Generated by Django 5.0.6 on 2024-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='number_of_hours',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
