# Generated by Django 5.0.6 on 2024-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0003_alter_classperiod_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='number_of_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
