# Generated by Django 5.0.6 on 2024-07-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0004_alter_classperiod_number_of_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='end_time',
        ),
    ]
