# Generated by Django 5.0.6 on 2024-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0005_remove_classperiod_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='end_time',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='start_time',
            field=models.DateField(),
        ),
    ]
