# Generated by Django 4.2.15 on 2024-08-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_course_date_and_more'),
        ('classperiod', '0009_alter_classperiod_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_periods', to='course.course'),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='day_of_the_week',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
