# Generated by Django 4.2.15 on 2024-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0010_alter_classperiod_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
