# Generated by Django 4.2.15 on 2024-08-20 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0011_alter_classperiod_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='end_time',
            field=models.TimeField(default=datetime.date(2024, 8, 20)),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='start_time',
            field=models.TimeField(default=datetime.date(2024, 8, 20)),
        ),
    ]
