# Generated by Django 4.2.15 on 2024-08-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0012_alter_classperiod_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='start_time',
        ),
    ]
