# Generated by Django 4.2.15 on 2024-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0013_remove_classperiod_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
