# Generated by Django 4.2.15 on 2024-08-21 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='John', max_length=20)),
                ('last_name', models.CharField(default='Doe', max_length=20)),
                ('email', models.EmailField(default='email@example.com', max_length=254)),
                ('code', models.PositiveSmallIntegerField(default=0)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('country', models.CharField(default='Country', max_length=20)),
                ('bio', models.TextField(default='No bio provided')),
                ('guardian_name', models.CharField(default='Guardian Name', max_length=255)),
                ('gender', models.CharField(default='Not Specified', max_length=30)),
                ('class_enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schoolclass.schoolclass')),
            ],
        ),
    ]
