# Generated by Django 4.2.15 on 2024-08-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='',
        ),
    ]
