# Generated by Django 5.0.6 on 2024-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
