# Generated by Django 5.0.6 on 2024-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_age_remove_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=1),
        ),
    ]
