# Generated by Django 4.2.15 on 2024-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
