# Generated by Django 4.2.15 on 2024-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_bio_remove_student_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(default='bio'),
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='country', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='gender', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='gn', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='country', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
