# Generated by Django 4.2.15 on 2024-08-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0005_schoolclass_classroom_course_and_more'),
        ('student', '0007_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_enrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schoolclass.schoolclass'),
        ),
    ]
