# Generated by Django 5.0.6 on 2024-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveSmallIntegerField()),
                ('class_number', models.PositiveSmallIntegerField()),
                ('class_trainer_name', models.CharField(max_length=20)),
                ('class_location', models.CharField(max_length=20)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_level', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=15)),
                ('class_days', models.PositiveSmallIntegerField()),
                ('class_student_names', models.TextField()),
                ('class_course', models.CharField(max_length=25)),
            ],
        ),
    ]
